apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-app-server
  labels:
    app: istio-demo-app-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: istio-demo-app-server
    spec:
      containers:
        - name: demo-app-server-container
          image: gcr.io/istio-hybrid/demo-app-server:live
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
