# HEADLESS demo-app-service with NO selectors
kind: Service
apiVersion: v1
metadata:
  name: demo-app-service
  # Service has no selectors
spec:
  # Service is HEADLESS
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
